### ISSUE TITLE
Gestion de la pagination

### ISSUE THREAD

**Issue by hawezo** [4sucres/board#11]
Sur téléphone, la pagination sort du conteneur et déforme la mise en page quand il y a trop d'options. 
Je vois deux solutions : faire en sorte que les éléments de pagination retournent à la ligne (flexbox ?), ou afficher moins de pages possibles.

![](https://i.imgur.com/JbKxwp5.png) 

Je préfère la deuxième solution dans la mesure où, quand il y a 12 pages, je serais peut-être intéressé d'accéder aux pages 1, 2, 3, 10, 11, 12, mais beaucoup moins intéressé d'accéder aux pages 4, 5, 6, 7 et 8.

**Comment by mgkprod** [comment]
En attendant mieux, je propose ça :

![chrome_euEKy8XSIv](https://user-images.githubusercontent.com/33329579/58036948-8f08b200-7b2c-11e9-8773-2c887e2d8652.png)
![chrome_WRwC9WAtyZ](https://user-images.githubusercontent.com/33329579/58036953-916b0c00-7b2c-11e9-9ea2-358b9e527c3b.png)
![chrome_Fph9DhJ70y](https://user-images.githubusercontent.com/33329579/58036958-929c3900-7b2c-11e9-8616-d02f2d7743d7.png)
