### ISSUE TITLE
Collision entre les mentions et la balise @

### ISSUE THREAD

**Issue by hawezo** [4sucres/board#14]
La balise @ est en conflit avec le système de mention. Les fixs possibles sont de changer le caractère de la balise, ou de changer le RegEx de celle-ci.
Exemple : https://4sucres.org/d/401-lhistoire-de-4sucres

**Comment by mgkprod** [comment]
J'ai modifié le tag ici : https://github.com/4sucres/board/commit/5a30d2af90c4599480bdd824f321c5054e6818da
