### ISSUE TITLE
Les changements d'onglets dans les modals bougent le scroll

### ISSUE THREAD

**Issue by mgkprod** [4sucres/board#16]
Exemple :

![4xS5a1g2xo](https://user-images.githubusercontent.com/33329579/58037564-f410d780-7b2d-11e9-9699-c83ad9d1a5a6.gif)

Peut être un conflit avec :

https://github.com/4sucres/board/blob/e3f6c80ee1dbc2dbbbbb7c4832a9ad7d43750ce6/resources/js/app.js#L598-L608

**Comment by hawezo** [comment]
C'est bien cette ligne qui pose soucis. 
https://github.com/4sucres/board/blob/e3f6c80ee1dbc2dbbbbb7c4832a9ad7d43750ce6/resources/js/app.js#L598

Ça sera réglé quand dans ma PR pour la réorganisation du JS.

```javascript
$('a[href^="#p"]').click(function(e)
```
