### ISSUE TITLE
Ajout de la balise ~Aesthetic~

### ISSUE THREAD

**Issue by mgkprod** [4sucres/board#19]
Visiblement, il va falloir passer par un coup de JS, impossible de reproduire le même comportement du script en question en PHP.

Balise : `~Aesthetic~`
Délimiteur : `~`

Script à "hook" :

https://github.com/prasiman/vaporwave-text-generator/blob/076f9419c7e104038528530c32b425a6a78d2226/script.js#L16-L28

**Comment by hawezo** [comment]
Le code est pas très beau mais je comprends pas pourquoi on ne pourrait pas reproduire son comportement en PHP.

J'ai écrit cette fonction vite fait en reprenant le modèle du code que tu as donné : 
```php
function vaporwave(string $input) 
{
    $output = '';
    for ($i = 0; $i < strlen($input); $i++) {
        $char = $input[$i];
        list(, $code) = unpack('N', mb_convert_encoding($char, 'UCS-4BE', 'UTF-8'));
        if ($code >= 33 && $code <= 270) {
            $output .=  mb_convert_encoding('&#' . intval($code + 65248) . ';', 'UTF-8', 'HTML-ENTITIES');
        } elseif ($code == 32) {
            $output .= chr($code);
        }
    }

    return trim($output);
}```

Ce qui donne : 
```console
λ php vaporwave.php
Ｖａｐｏｒｗａｖｅ Ａｅｓｔｈｅｔｉｃ
```
Lors de l'appel suivant : `vaporwave('Vaporwave Aesthetic');`.
J'ai pas testé beaucoup de cas évidemment, mais en partant du principe que la fonction Javascript donnée fonctionne, celle-ci devrait également être correcte.

**Comment by mgkprod** [comment]
Noté, j'implémente ça de suite.

**Comment by Edou68FR** [comment]
Certains caractères utilisant de l'accentuation, retourne des points d'interrogations et ne sont donc pas convertis en UCS4BE, voir [ce post.](https://4sucres.org/p/6041)
Remplacer ces caractères par leur équivalent sans accent serait une solution.

|  Caractère : séparé par ; | è;é;ê;ë | ò;ó;ô;õ;ö | ù;ú;û;ü | à;á;â;ã;ä | ç |
|---------------------------|---------|-----------|---------|-----------|---|
| équivalent :              | e       | o         | u       | a         | c |

**Comment by hawezo** [comment]
Il y a possibilité d'utiliser le [Transliterator](https://www.php.net/manual/fr/class.transliterator.php) de PHP pour éviter de réinventer la roue. 
```php 
transliterator_transliterate('Any-Latin; Latin-ASCII;', $input);
```
J'ai pas cherché plus loin pour le code caractère à mettre, mais ça prend en charge la plupart des caractères spéciaux : 

```console
λ php vaporwave.php
Input: áÁàÀăĂâÂåÅãÃąĄāĀäÄæÆḃḂćĆĉĈčČċĊçÇďĎḋḊđĐðÐéÉèÈĕĔêÊěĚëËėĖęĘēĒḟḞƒƑğĞĝĜġĠģĢĥĤħĦíÍìÌîÎïÏĩĨįĮīĪĵĴķĶĺĹľĽļĻłŁṁṀńŃňŇñÑņŅóÓòÒôÔőŐõÕøØōŌơƠöÖṗṖŕŔřŘŗŖśŚŝŜšŠṡṠşŞșȘßťŤṫṪţŢțȚŧŦúÚùÙŭŬûÛůŮűŰũŨųŲūŪưƯüÜẃẂẁẀŵŴẅẄýÝỳỲŷŶÿŸźŹžŽżŻþÞµаАбБвВгГдДеЕёЁжЖзЗиИйЙкКлЛмМнНоОпПрРсСтТуУфФхХцЦчЧшШщЩъЪыЫьЬэЭюЮяЯ
Output: ａＡａＡａＡａＡａＡａＡａＡａＡａＡａｅＡＥｂＢｃＣｃＣｃＣｃＣｃＣｄＤｄＤｄＤｄＤｅＥｅＥｅＥｅＥｅＥｅＥｅＥｅＥｅＥｆＦｆＦｇＧｇＧｇＧｇＧｈＨｈＨｉＩｉＩｉＩｉＩｉＩｉＩｉＩｊＪｋＫｌＬｌＬｌＬｌＬｍＭｎＮｎＮｎＮｎＮｏＯｏＯｏＯｏＯｏＯｏＯｏＯｏＯｏＯ
ｐＰｒＲｒＲｒＲｓＳｓＳｓＳｓＳｓＳｓＳｓｓｔＴｔＴｔＴｔＴｔＴｕＵｕＵｕＵｕＵｕＵｕＵｕＵｕＵｕＵｕＵｕＵｗＷｗＷｗＷｗＷｙＹｙＹｙＹｙＹｚＺｚＺｚＺｔｈＴＨ？？ａＡｂＢｖＶｇＧｄＤｅＥｅＥｚＺｚＺｉＩｊＪｋＫｌＬｍＭｎＮｏＯｐＰｒＲｓＳｔＴｕＵｆＦｈＨｃＣ
ｃＣｓＳｓＳ＂＂？？ｙＹ＇＇？？ｅＥｕＵａＡ
```

Voici le code mis à jour : 
```php
function vaporwave(string $input) 
{
    $input = transliterator_transliterate('Any-Latin; Latin-ASCII;', $input);
    $output = '';
    for ($i = 0; $i < strlen($input); $i++) {
        $char = $input[$i];
        list(, $code) = unpack('N', mb_convert_encoding($char, 'UCS-4BE', 'UTF-8'));
        if ($code >= 33 && $code <= 270) {
            $output .= mb_convert_encoding('&#' . intval($code + 65248) . ';', 'UTF-8', 'HTML-ENTITIES');
        } elseif ($code == 32) {
            $output .= chr($code);
        }
    }

    return trim($output);
}
```

(cc @mgkprod)
