### ISSUE TITLE
Caroussel avec les bannières

### ISSUE THREAD

**Issue by mgkprod** [4sucres/board#23]
Il est beau, il est là, il est responsive et compatible mobile (swipe!), c'est OwlCaroussel : https://owlcarousel2.github.io/OwlCarousel2/

Intégrer ça en lieu et place de la bannière, avec les deux banières du repo qui se battent en duel.

**Comment by hawezo** [comment]
À éviter de faire avant #12 pour ne pas compliquer le merge à venir.

**Comment by hawezo** [comment]
Résolu avec #91.
