### ISSUE TITLE
Nouvelles catégories "custom"

### ISSUE THREAD

**Issue by mgkprod** [4sucres/board#32]
Étape 1. "Sécuriser" les catégories avec des filtres d'accès.
- Filtre "connecté"
- Filtre "majorité"
- Filtre "roles"

Étape 2. Et créer les catégories suivantes :

**Catégorie #nsfw**
- Interdite aux membres non connectés
- Interdite au mineurs (`User::class()->dob`)

**Catégorie #supporter**
- Interdite aux membres non connectés (évidemment)
- Réservée au rôle "supporter" (et modération, évidemment)

--------

Des choses à rajouter @hawezo ?

**Comment by hawezo** [comment]
Rien à ajouter, hormis peut-être l'ajout d'une catégorie **#hobbies** pour parler des passions des uns et des autres (développement, anime).

**Comment by mgkprod** [comment]
Putain c'est ça qui faut, un système de références !
