### ISSUE TITLE
Nouvelles catégories

### ISSUE THREAD

**Issue by mgkprod** [4sucres/board#33]
Rien à ajouter, hormis peut-être l'ajout d'une catégorie **#hobbies** pour parler des passions des uns et des autres (développement, anime).

_Originally posted by @hawezo in https://github.com/4sucres/board/issues/32#issuecomment-494111041_

Même avec le système de "flair", certain de vouloir mélanger #hobbies et #développement ?
Il va falloir vraiment bien l'intégrer, j'ai encore du mal à me l'imaginer, mais je me voispas chercher mes petits devs parmi les kj D:

**Comment by hawezo** [comment]
Le principe des flairs ce serait de pouvoir filtrer, pour pouvoir afficher tous les topics avec un certain flair. Avec Vue ça me paraît faisable, tu en penses quoi ?

Personnellement je vois mal une catégorie spéciale kj sur un forum comme ça, mais si tu y vois pas d'inconvénient, c'est pas moi que ça va déranger.
