### ISSUE TITLE
(Supporter) Upload gif animé en tant qu’avatar

### ISSUE THREAD

**Issue by mgkprod** [4sucres/board#35]
- Augmenter la taille maximale allouée pour l'envoi
- Trouver un moyen de resize (soit au stockage, soit à l'affichage) pour qu'il fit correctement dans le l'interface du forum

**Comment by hawezo** [comment]
> Trouver un moyen de resize (soit au stockage, soit à l'affichage) pour qu'il fit correctement dans le l'interface du forum

Habituellement j'utilise la librairie [Imagine](https://github.com/avalanche123/Imagine), qui a un bundle Symfony. Une petite recherche a donné ce wrapper pour Laravel : https://github.com/orchestral/imagine, ça conviendrait ?

**Comment by mgkprod** [comment]
> Habituellement j'utilise la librairie [Imagine](https://github.com/avalanche123/Imagine), qui a un bundle Symfony. Une petite recherche a donné ce wrapper pour Laravel : https://github.com/orchestral/imagine, ça conviendrait ?

Yep, bonne idée, c'est compatible avec les gifs animés, contrairement à `Intervention/image` qui est utilisé actuellement. Si on veut faire le truc proprement, il faudrait utiliser Imagine à la place d'Intervention du coup, pour l'existant aussi.
