### ISSUE TITLE
Cliquer sur le .row ramène sur le post

### ISSUE THREAD

**Issue by mgkprod** [4sucres/board#36]
Scope: Liste des topics

Corriger le hook de clic sur toute la ligne pour rétablir le bon comportement du Ctrl+clic (nouvel onglet)

+ Ajouter le alt+clic pour aller directement au dernier message
+ Paramètre utilisateur pour inverser le comportement ?

**Comment by mgkprod** [comment]
015994d030328788fc0a883da1dad02d67beeb1c
ec786b3408f2d7dcc15256de7028a2f6737ed423

**Comment by hawezo** [comment]
Je pense qu'il faudrait l'appliquer également aux messages épinglés, non ? @mgkprod

**Comment by hawezo** [comment]
Autre idée qui ne mérite peut-être pas un nouveau ticket : le `Alt + Clic` marque le topic comme lu ?
