### ISSUE TITLE
Affichage des dates

### ISSUE THREAD

**Issue by mgkprod** [4sucres/board#43]
Je trouverais ça sympa que l'affichage des dates soit un peu plus intelligent que d'afficher le classique `le d/m/Y a H:i:s`, par exemple, on pourrait afficher Aujourd'hui/Hier à la place de la date :

Avant :
![image](https://user-images.githubusercontent.com/33329579/58093996-f166be80-7bcf-11e9-9aba-ef644a536e79.png)

Après :
![image](https://user-images.githubusercontent.com/33329579/58094034-07747f00-7bd0-11e9-809e-fb5edd4fbfd9.png)

Il serait aussi possible facilement d'afficher aveec le `diffForHumans()` de Carbon un texte de ce genre :
![image](https://user-images.githubusercontent.com/33329579/58094110-296e0180-7bd0-11e9-8f41-9a85da8b5c97.png)

En gros ce que je propose :
- Si c'est posté le jour même : `aujourd'hui il y a (i minutes|H heures)`
- Si c'est posté la veille : `hier à H:m:s`
- Si c'est antérieur : `le d/m/Y à H:i:s`

Votre avis avant réalisation ?

**Comment by hawezo** [comment]
Liaison possible avec https://github.com/4sucres/board/issues/44#issuecomment-494424923.

**Comment by mgkprod** [comment]
Résolu dans : 93e80d374103070032b8c5347bd7f7ad0199d7d8
