### ISSUE TITLE
Ancienneté dans le profil

### ISSUE THREAD

**Issue by mgkprod** [4sucres/board#44]
![image](https://user-images.githubusercontent.com/33329579/58094366-ccbf1680-7bd0-11e9-93fe-f922301fa0c7.png)

L'affichage de l'ancienneté dans le profil n'est pas bon pour les tous membres inscrits dans les dernières 24h. C'est une erreur d'affichage.

En effet, le calcul actuel est : _Si le membre est inscrit depuis moins d'une journée, on affiche "aujourd'hui"_
Or, il faudrait : _Si le membre est inscrit **depuis le début de la journée**, alors on affiche aujourd'hui_
(il faudra faire attention aussi à "Membre depuis 0 jours" qui pourra apparaître)

Pour l'instant la modification s'effectue ici en attendant un refacto pour tout bouger dans le controller :

https://github.com/4sucres/board/blob/6b911edf1f7a1f4f2a296c879b075ac8e2555a6a/resources/views/user/show.blade.php#L33

(l'image c'est uniquement pour le contexte, le "bug" n'est pas présent dessus)

**Comment by hawezo** [comment]
Je pense qu'il faut éviter de faire ça à la main, parce que des librairies existent précisément pour ce genre de problème récurrent. 

Ma référence dans Symfony est intégrée à Twig, mais en PHP, [Carbon](https://carbon.nesbot.com/) est connue. 

La fonctionnalité qui nous intéresse est là : https://carbon.nesbot.com/docs/#api-humandiff. 

Autres ressources :
- https://janostlund.com/2018-06-21/laravel-locale
- https://laracasts.com/discuss/channels/laravel/use-the-localisation-of-laravel-for-carbon?page=1

**Comment by mgkprod** [comment]
Il me semblait important de l'afficher en "jours", le choix est volontaire.

**Comment by hawezo** [comment]
> Il me semblait important de l'afficher en "jours", le choix est volontaire.

Comme ça ?
```php
echo Carbon::now()->subDays(5)->diffForHumans(); // 5 days ago
```

**Comment by mgkprod** [comment]
https://github.com/4sucres/board/issues/44#issuecomment-494426705
Comment il se comporte au bout de quelques mois, quelques années ? Il me semble qu'on perds la précision et qu'on arrive dans des `x months ago`

**Comment by hawezo** [comment]
Est-ce que [ces options](https://github.com/briannesbitt/Carbon/blob/master/src/Carbon/CarbonInterface.php#L501-L513) peuvent aider ?
