### ISSUE TITLE
Affichage "En ligne"

### ISSUE THREAD

**Issue by mgkprod** [4sucres/board#45]
Au lieu d'afficher "En ligne" / "Hors ligne", afficher la dernière présence (dans la limite de quelques heures, comme sur Messenger)

![image](https://user-images.githubusercontent.com/33329579/58094824-d39a5900-7bd1-11e9-8d61-273728bd9656.png)![image](https://user-images.githubusercontent.com/33329579/58094813-ce3d0e80-7bd1-11e9-9efb-4d20d4dad7b0.png)![image](https://user-images.githubusercontent.com/33329579/58094842-dd23c100-7bd1-11e9-9c8e-34924b534dad.png)

**Comment by hawezo** [comment]
J'approuve. Possible lien avec https://github.com/4sucres/board/issues/44#issuecomment-494424923 pour la dernière présence.
