### ISSUE TITLE
Nouveaux achievements "automatiques"

### ISSUE THREAD

**Issue by mgkprod** [4sucres/board#48]
![image](https://user-images.githubusercontent.com/33329579/58097522-e9ab1800-7bd7-11e9-8c57-5ea941b2b0e2.png)
![image](https://user-images.githubusercontent.com/33329579/58097534-f0d22600-7bd7-11e9-9e0b-5e6177579cac.png)

La liste se remplit au fur et à mesure, certains sont encore en cours de réalisation chez le graphiste.

Au passage :
- Ajouter une notification en cas d'ajout d’attribution d'un succès et la lancer aux utilisateurs lors de l'ajout par un modérateur/administrateur
- Ajouter une notification en cas de changement de "classification" par un modérateur/administrateur (c'est sensé être un événement exceptionnel pour les utilisateurs)

Direction technique à prendre :
- Tâche programmée qui va vérifier régulièrement l'état du forum et ajouter les succès aux utilisateurs
**OU**
- Verrues un peu partout dans le code, calculées à chaque ajout de post/création de discussion/..., pour attribuer le succès à l'utilisateur en temps réel ?

@hawezo ton avis ?

**Comment by hawezo** [comment]
J'imagine une solution telle qu'un `Achievement` est définit par une classe qui possède une fonction `canUnlock($user)`.

Cette fonction ferait les vérifications nécessaires permettant de définir si l'utilisateur passé en argument possède les pré-requis pour débloquer ce succès.

Je verrais une autre classe, `AchievementManager`, gérer la vérification et l'attribution par lot. Voici une interface possible :

```php

interface AchievementManagerInterface
{
    
    /**
     * Boucle dans `$possibleAchievements` pour appeler la fonction
     * `$canUnlock` de chacun d'eux en passant `$user`.
     */
    public function canUnlock(User $user, array $possibleAchievements) {}

   /**
    * Débloque le succès `$achievement` pour l'utilisateur donné et le notifie.
    */
    public function unlock(User $user, Achievement $achievement) {}

    /**
    * Vérifie tous les succès pour tous les utilisateurs.
    */
    public function probe() {}
}
```

Dans cet exemple, la fonction `probe()` devrait être appelée par tâche planifiée la nuit, et la fonction `canUnlock()` lors d'évènements récurrents dont les succès sont faciles à vérifier.

Par exemple dans le contrôleur qui gère la création de messages : 
```php
// DiscussionController.php

public function store()
{
    $discussion = Discussion::create(); //...

    // Vérifie les succès probables pour ce cas
    $achievementManager->canUnlock(user(), [
        CrazyPosterAchievement::class, // Avoir posté 500 messages
        RegularPosterAchievement::class, // Avoir posté 100 messages
        // ...
    ]);
}
```

**Comment by hawezo** [comment]
Je veux bien m'en occuper, au passage. Ça me permettra d'en apprendre un peu plus sur Laravel et c'est intéressant à implémenter. T'es d'accord @mgkprod ?
