### ISSUE TITLE
Popup URL dans les posts

### ISSUE THREAD

**Issue by mgkprod** [4sucres/board#56]
![image](https://user-images.githubusercontent.com/33329579/58108614-74960d80-7bec-11e9-8773-32f2a8978333.png)

ça déconne !

**Comment by hawezo** [comment]
Le `$url` est intégré directement dans la chaîne au lieu d'être concaténé ? 
https://github.com/4sucres/board/blob/master/app/Helpers/sucresParsedown.php#L147-L151

**Comment by mgkprod** [comment]
Le type qui a fait ça devait être vraiment fatigué !
