### ISSUE TITLE
Mise en cache et taille des stickers

### ISSUE THREAD

**Issue by mgkprod** [4sucres/board#65]
Avec la mise en cache des posts il est, à première vue, plus possible de définir la taille des stickers selon l'utilisateur qui consulte le post (sachant que le cache est mutualisé).

J'ai temporairement désactivé le fait de rendre les stickers en "inline" : https://github.com/4sucres/board/commit/bd2e8aac54975987a046082ddeb55150ef1b5cc9

**Comment by hawezo** [comment]
Comment la mise en cache des posts fonctionne et pourquoi est-elle nécessaire ? Est-ce que c'est par rapport à #57 ?

Mon avis sur la question du cache par rapport à Imgur était de mettre en cache le résultat de l'API en fonction de l'ID de l'image, et pas de mettre en cache le post complet, qui aurait en effet comme contrepartie de bloquer les fonctionnalités de paramétrage.
