### ISSUE TITLE
Cacher l'éditeur pour les non connectés

### ISSUE THREAD

**Issue by Edou68FR** [4sucres/board#76]
Quand nous ne sommes pas connectés sur 4sucres.org, et qu'on se rend sur un topic, l'éditeur est disponible, la personne serait capable de rédiger un message, de cliquer sur "élever le débat". Elle tombe sur la page de _login_/_register_ et une fois connectés, elle est redirigée vers la page d'accueil de 4sucres.org.
La personne perd donc son message inscrit précédemment. 

J'avais pensé à quelque chose qui pourrait régler ce problème la, et également rajouter un petit plus.
Pourquoi pas stocker le contenu du message/topic dans le navigateur de l'utilisateur, ou dans la bdd ?
Je sais pas si c'est la bonne solution technique, mais disons que pouvoir refresh son navigateur sans avoir à préalablement copier son post est utile.

**Comment by mgkprod** [comment]
On va rendre l'éditeur indisponible pour les gens non connectés.

**Comment by mgkprod** [comment]
> J'avais pensé à quelque chose qui pourrait régler ce problème la, et également rajouter un petit plus.
> Pourquoi pas stocker le contenu du message/topic dans le navigateur de l'utilisateur, ou dans la bdd ?
> Je sais pas si c'est la bonne solution technique, mais disons que pouvoir refresh son navigateur sans  avoir à préalablement copier son post est utile. 

Non, parce qu'après les gens vont se plaindre d'avoir des trucs qui restent entre les pages, genre brouillon etc.

**Comment by hawezo** [comment]
> Non, parce qu'après les gens vont se plaindre d'avoir des trucs qui restent entre les pages, genre brouillon etc.

Pas forcément. Pour bien faire, on pourrait rendre ça paramétrable. 
Pour le côté technique, un simple stockage dans le navigateur ferait l'affaire (genre http://cfurrow.github.io/jquery.autosave.js/)
