### ISSUE TITLE
Affichage des messages supprimés

### ISSUE THREAD

**Issue by hawezo** [4sucres/board#77]
Pour les membres n'ayant pas la permission de les voir, ils sont très bien, mais quand on a la permission ça fait juste étrange de le voir sous l'annotation. 

Je propose de changer l'affichage en faveur d'un [collapse](https://getbootstrap.com/docs/4.3/components/collapse/). 

**Exemples**

![](https://i.imgur.com/z5Mqucw.png)

![](https://i.imgur.com/R9llACG.png)

---

Je propose également l'ajout d'une option de restauration de message, disponible pour l'auteur et aux modérateurs (potentiel lien avec #60).

**Comment by mgkprod** [comment]
> Je propose également l'ajout d'une option de restauration de message, disponible pour l'auteur et aux modérateurs (potentiel lien avec #60).

Duplicate : #37

**Comment by hawezo** [comment]
> Duplicate : #37

Si par "post" tu entendais "message", alors oui
